### ISSUE TITLE
Web App should fully fingerprint and cdn-ify assets

### ISSUE THREAD

**Issue by kenperkins** [deconst/deconst-docs#13]
Static assets for the app (Javascript, CSS, images, etc) should be fingerprinted (with a unique name) and published to a CDN (or using a CDN origin server). In addition, we want to ensure the headers from the CDN have an expires of a ridiculously long time, say 1 year minimum.

**Comment by smashwilson** [comment]
Here's the way I'm currently thinking of implementing this:
1. Add a `POST /asset` call to the content service. Accept an asset, generate its checksum, and upload it to Cloud Files with a fingerprinted filename in a CDN-enabled asset container. Return the full URL to the fingerprinted asset.
2. Within each preparer, upload static assets to the content service _first_. Build a map of local asset path :point_right: fingerprinted asset URL using the responses. When generating image links, do a lookup and use the asset URL if one is available.

I keep trying to think of a way to make this happen behind the content service API, to keep us from needing to implement static content handling differently within each presenter, but I don't think that's feasible because (a) presentation engines differ so drastically in their treatment of static content and (b) the content service accepts content a single piece at a time, so it would be prohibitively complex to know which URLs to rewrite to which other URLs.

The other bit of this is handling static assets that are distributed as part of the layout and site chrome. It would be convenient to include an asset pipeline there, to do things like CSS and JS minimization and concatenation. I'm thinking that we can add a `static` directory to the control repository for those assets to live in and use a Travis build to publish them - although I'm not sure how to communicate the asset URLs back to the layouts. Probably magic variables that can be used in the templates?

**Comment by smashwilson** [comment]
And now content repository assets are being processed and served properly, from the Sphinx preparer:

http://deconst.devsupport.me/running/architecture/

:sparkles:

(At least images... there are also static resources, extra files, and a few other resources I'll probably need to investigate.)

**Comment by smashwilson** [comment]
Now handling static assets associated with the layouts, as well. :metal:

**Comment by jrperritt** [comment]
Awesome :)
