### ISSUE TITLE
Local builds for content repositories

### ISSUE THREAD

**Issue by smashwilson** [deconst/deconst-docs#9]
Documentation writers need a way to easily preview the content they're authoring locally, in an environment as close as possible to what the live build will do. Mostly, this means using the same layouts (#6) (or at least, layouts kept consistent with the real ones automatically).

Some considerations here:
- We want to make user experience for this as smooth as possible so the writers can focus on writing, not yak shaving. Jekyll in particular (for the blog) is kind of a pain to set up properly. I'm not convinced that a `pip install` would be any better (and in fact, in some ways, would likely be worse). Docker smooths these issues - but now they need to install and manage _Docker_.
- Build-on-file change is a must, in my opinion, and it needs to be responsive. Automatic browser refresh would be awesome but probably trickier.
- What platforms do we need to support? Mostly Mac, I expect, but are their outliers?
- We'll want to engage with the doc writers directly, and early, to expose pain.

**Comment by kenperkins** [comment]
In a perfect world, all of the templates and assets would be shared globally so that there's no duplication, but that may not be the fast path to shipping. It might be easier, for the time being, to just have a duplicated template in the jekyll and sphinx repos until we can before factor that part of the platform.

**Comment by kenperkins** [comment]
@smashwilson what's wrong with just running jekyll or sphinx in the local directory, and not having any runtime component?

**Comment by smashwilson** [comment]
> In a perfect world, all of the templates and assets would be shared globally so that there's no duplication, but that may not be the fast path to shipping. It might be easier, for the time being, to just have a duplicated template in the jekyll and sphinx repos until we can before factor that part of the platform.

Sure. I didn't include this in the 0.1 milestone, for example; it might not even make the initial launch. I wanted to start the conversation early, though.

> @smashwilson what's wrong with just running jekyll or sphinx in the local directory, and not having any runtime component?

Because that assumes the doc writers have Jekyll or Sphinx installed and configured just so. In the past, we've found that this is a poor assumption.

It sounds easy to say "just install Jekyll to contribute to the blog," but in practice that causes a lot of pain for contributors. Why? Because installing Jekyll assumes that you have a Ruby installation, and not just that but a _sane_ Ruby installation that's a recent version using rvm or rbenv or chruby or pik, and Bundler installed, and all of your permissions right and none of your system libraries broken. Oh, and I think Jekyll needs node.js installed as well, I think to support JavaScript minimization or what have you.

The Sphinx situation is a little better, because the system Python on a stock Mac is less terrible than the system Ruby. It's not great, though, because you need to do the pip dance, and should probably be using a virtualenv and so on. When I was chatting with the docs writers about this a little at rax.io they mentioned that keeping the right Sphinx plugins installed and configured just so was a concern.

This is why we eventually changed the current d.r.c. to use a Vagrant box for local development. That replaced these yak-shaving problems with a new set of yak-shaving problems, because now contributors needed to install VirtualBox and Vagrant, and the Vagrant box took forever to download, and then the provisioning was janky and would break often without us noticing, because it took forever to run on a clean box and we wouldn't be able to see things break.

That was why I moved the build environment into a Docker container: absolute consistency for everyone running the build. You _still_ need to shave a yak to set it up, by installing Docker, which I tried to automate in the script with limited success.

That's where I am on this today. I want to make the process as absolutely turn-key, consistent, and automated as possible for contributors, not least of which the docs writers. I want to make setup from nothing as painless as possible, so that blog contributors can preview their contributions without having to spend a day wrestling with it first. I want to make build details transparent to writers and contributors so we can use packages and plugins and custom code all we want without imposing a burden on them. I want to be able to change things under the hood and have everyone's build environments update in a reasonable way. I don't believe that running Sphinx or Jekyll directly accomplishes all of these goals.

So that's why I have this issue: to figure out the most reasonable thing we can do that satisfies those constraints.

**Comment by kenperkins** [comment]
@smashwilson great to have your thoughts on paper.

I believe there are two primary use cases we should consider here:
1. A one-off contributor. Think of this as the drive-by bug-fixer or blog-author
2. Regular contributors. Doc writers, devs on DevEx, rackers who blog often, etc.

Thinking outloud here:
- Do we optimize for one of these workflows at the expense of the other?
- Are there ways to do both?
- Should we expect the one-off person to even bother with local setup?
- Can drive-by commiters just commit & PR and use our CI/CD process for review?

**Comment by kenperkins** [comment]
Also, it sounds like @annegentle might be doing some work here...

**Comment by chesshacker** [comment]
What if we didn't try to make a website preview?  What the writer really needs to see is that their markup is rendered in a way that makes sense.  What if we standardized on an editor like Sublime and used its preview feature?  There could be other reStructuredText editors out there that are cross-platform and provide a preview feature.

**Comment by kenperkins** [comment]
Do you have any concern about prescribing a specific editor? We also have to address content repositories in other formats, i.e. markdown/jekyll front matter, etc.

**Comment by chesshacker** [comment]
The writers are already used to using a specific editor.  And it's not to say they couldn't use a different one... we would just offer them a standard tool that meets their needs.  If others want to venture off and try different editors with different preview capabilities, that's cool too.
More text editor options are listed here: http://wiki.typo3.org/Editors_(reST)

**Comment by smashwilson** [comment]
I don't know about writers, but prescribing a forced editor on a group of developers is a wonderful way to drive them to their pitchforks and torches :laughing:

Maybe local markdown or reStructuredText previewing would be good enough, I don't know. My instinct is to offer a local build that's as close to the final product as possible, to avoid surprises like having an image caption that's too long and breaks the layout, say - but that's just my instinct. :bow:

**Comment by rgbkrk** [comment]
I think the point anyway is that anyone can contribute with their own choice of editor, including GitHub's built in one.

**Comment by chesshacker** [comment]
All good discussion, but my intent was not we enforce a specific editor.  It was that the writers could use the built-in reST preview feature of an editor.  Sublime has this capability, as do other editors. http://wiki.typo3.org/Editors_(reST)

**Comment by chesshacker** [comment]
Another option I mentioned in Slack that I want to add here is building a self-contained tool in python to generate previews, and distributing it with py2app and py2exe.  I don't think we can realistically expect all the content contributors to install docker or vagrant or pip or any other yak shaving.  I think either using a text editor that has preview capability built-in, or building a tool that makes previews easy is the way to go.  I also do not think it needs to be an exceedingly high-fidelity preview matching the latest and greatest website layout.  It needs to produce simple HTML that we can apply some nice styles too.  The writers need a way to see that their reST markup produces the expected HTML.

**Comment by smashwilson** [comment]
:+1: the more I think about this for distributing any local builder as an app.

I've also been considering using [Electron](http://electron.atom.io/) (formerly atom-shell) for this. It not only builds a native-looking Mac app and a proper Windows installer, but it also gives you automatic, silent updates. It's built for node.js apps, but:
1. That's going to be easier to integrate deconst code into anyway, because the presenter is all node.js;
2. We can shell out to bundled Python and Ruby executables for the Sphinx and Jekyll builds.

**Comment by rgbkrk** [comment]
Wow, electron is slick.

**Comment by smashwilson** [comment]
Yay @rgbkrk is back!

**Comment by rgbkrk** [comment]
~~Now that you see me, why build a full application instead of an Atom plugin?~~

Nevermind, I see where the :fire: war came up:

> prescribing a forced editor on a group of developers is a wonderful way to drive them to their pitchforks and torches

**Comment by ianthewhite** [comment]
@kenperkins my team has alot of feels on this subject, please engage them in the discussion.

**Comment by smashwilson** [comment]
@ianthewhite Yeah absolutely, that is the intention (and also why we haven't really touched any implementation of this yet).

Also please feel free to make your priorities and wants on this front known by commenting here :smile:

**Comment by meker12** [comment]
So what we have been doing in the docs-migration repo:

Local sphinx build of RST content. 

Preview in editor of choice;  been using http://rst.ninjs.org/   for html preview, but no styles. To try: http://ericholscher.com/blog/2013/oct/1/sphinx-live-preview/  -- assuming that will render some Sphinx specific things like cross-references with :ref:

Local Sphinx build uses a theme that Anne cobbled together.  Styles and layout are not perfect, but not too bad either.

I've wanted to try the Typo3 Sphinx that Steve suggested:  http://typo3.org/extensions/repository/view/sphinx  -- Seems promising.

Environment requirements: 
Virtualenv install of Sphinx 
Local RST editor of choice

If we have styles that are as close to the website as possible, it's better because it allows writers to notice stylistic issues that might need to be addressed at the template level.

I believe it is a good idea for all writers to have the capability and experience of installing the whole build system via Docker at least once.  Working with the guts helps understand the architecture better and helps writers have more insight into troubleshooting issues.  Having hands on experience with the build system also builds a shared vocabulary and understanding between all the teams that work to create the system:  UX design, Dev, DocTools, and Wrtier/contributors.

**Comment by meker12** [comment]
In the last paragraph- what I mean is that having all the people using the tool have a good understanding of the different components and how it works so that its easier to describe and resolve any issues that come up.   Because all of the parts are abstract, it helps to have hands on experience or maybe a demo video showing someone installing and testing the different parts.  

As far as contributing, designing a system that considers the different contributor and contributor use cases is helpful, as Ken suggested. 

The model we have been following for the docs-migration has been working pretty well.  Anne and Zach can weigh in here.  Also, next week, we'll be having a Doc Swarm around RST, Sphinx, developing the content architecture, and hopefully some templating as well.  Having some deconst system, DocTools, and UX designers observe for awhile might be a great way to understand use cases and pain points.

**Comment by annegentle** [comment]
So, I go back and forth on the balancing act between "writers level up their dev knowledge" and "not everyone should have to have a dev enviro to write." There's a balancing act here and we're trying to find the fulcrum. For devdocs, it seems like a good learning opportunity to use docker and have Python/Sphinx working locally. For private cloud writers, they're going to want as much automation in their workflow as they can get since they're used to "build locally, push a button to publish when it's ready." 

So I think a local build should suffice to see what the HTML will look like. I personally prefer to see it all in context, so I like where @smashwilson is going with https://github.com/deconst/integrated. But I would also like to have a local "deliverable-only" build. I think that the local build can have requirements and I would prefer the editor be "anything." For migration, we made a simple Sphinx theme that mimics dev.rax, and it bootstraps us for now.

**Comment by smashwilson** [comment]
This now exists with [the Deconst client](https://github.com/deconst/client). It's a little rickety, but as it improves, it'll serve the use case for writers being able to preview the content they're authoring before they push content to GitHub.

It's far too heavyweight for the other use-cases, which are:
- To support drive-by contributors, and;
- To share rendered content with people on other teams before it's ready to go live.

Those two cases should be covered by the pull request builder, which is a different issue.
